volumes:
  postgres-data:

services:
  db:
    image: postgres:16.4
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=griffin
      - POSTGRES_PASS=griffin
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_PASSWORD=griffin
    ports:
      - 5432:5432
